#########################################
# The "production" compose file builds 
# on your EC2 instance
#########################################

version: "3"
services:
  api:
    image: $DOCKERHUB_UNAME/backend-prod:$NEW_VERSION 
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DEBUG=$DEBUG
      - DB_NAME=$POSTGRES_DB
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - API_KEY=$API_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    depends_on:
      - db
    volumes:
      - media_volume:/app/media  
  nginx:
    image: $DOCKERHUB_UNAME/webserver-prod:$NEW_VERSION
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  postgres_data:
  media_volume: 